### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [tryffel/bookmarker#1]
Dear @tryffel,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by tryffel** [comment]
The cross-compilation process is a troublesome, especially with sqlite3-support. I'm having problems with it especially with my other project, Jellycli, and I'm still resolving it. I don't have a working Windows installation atm, so it might take a while. For anyone: PR is welcome with e.g. drone & goreleaser config for successful cross-compilation for windows.

**Comment by tryffel** [comment]
Added binaries under release 0.1
